<a href="https://colab.research.google.com/github/Girawale-Sanket/Gen-AI-LLM-Assignment-/blob/main/Sentimential_Analysis_on_Feedback(BERT).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Zero Shot Classifier

In [1]:
!pip install -q transformers
from transformers import pipeline

classifier = pipeline("zero-shot-classification", model="facebook/bart-large-mnli")

print("Zero-shot classifier is loaded.")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/1.15k [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 1.63GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/515 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Zero-shot classifier is loaded.

In [2]:
reviews = [
    "This movie was absolutely wonderful, I loved every minute of it!",
    "The plot was boring and the acting was terrible.",
    "The service was so good, I only waited forty five minutes.",
    "I don't dislike it, but I wouldn't watch it again either."
]

labels = ["positive", "negative", "neutral"]

for review in reviews:
    result = classifier(review, candidate_labels=labels)
    top_label = result["labels"][0]
    top_score = result["scores"][0]

    print(f"Review: {review}")
    print(f"  → {top_label} (confidence {top_score:.3f})")
    print()

Review: This movie was absolutely wonderful, I loved every minute of it!
  → positive (confidence 0.981)

Review: The plot was boring and the acting was terrible.
  → negative (confidence 0.984)

Review: The service was so good, I only waited forty five minutes.
  → positive (confidence 0.963)

Review: I don't dislike it, but I wouldn't watch it again either.
  → negative (confidence 0.631)

***Assignment Work***

In [3]:
reviews=[
    "The discovery of liquid water on Europa is a groundbreaking milestone for space research.",
    "Budget cuts and constant launch delays are severely slowing down deep space missions.",
    "The new telescope has been deployed into orbit, but initial data transmission will take time."

]

labels = ["positive", "negative", "neutral"]

for review in reviews:
    result = classifier(review, candidate_labels=labels)
    top_label = result["labels"][0]
    top_score = result["scores"][0]

    print(f"Review: {review}")
    print(f"  → {top_label} (confidence {top_score:.3f})")
    print()

Review: The discovery of liquid water on Europa is a groundbreaking milestone for space research.
  → positive (confidence 0.946)

Review: Budget cuts and constant launch delays are severely slowing down deep space missions.
  → negative (confidence 0.922)

Review: The new telescope has been deployed into orbit, but initial data transmission will take time.
  → negative (confidence 0.460)

In [4]:
reviews = [

    "Although marine expeditions involve months of harsh sea conditions and mechanical failures, the discovery of thriving deep-sea ecosystems near hydrothermal vents makes the research team deeply appreciative of the vessel's advanced life-support systems.",

    "While the oceanographic institution routinely provides state-of-the-art sonar equipment and research funding, their persistent refusal to address crew exhaustion and safety concerns leaves researchers feeling completely expendable during offshore missions.",

    "Conducting deep-sea trench investigations creates a baffling dynamic; the excitement of gathering unprecedented biological data is immediately offset by overwhelming burnout and safety anxieties, leaving the crew's morale in an ongoing deadlock.",

    "The research team collects ocean salinity measurements every morning at six o'clock, logging standard hydrological metrics into the marine database without performing further biological sampling."

]

labels = [
    "positive",
    "negative",
    "neutral",
    "grateful",
    "emotional neglect",
    "toxic relationship"
]

for review in reviews:
    result = classifier(review, candidate_labels=labels, multi_label=True)

    print(f"Review: {review}")
    print("  Top predicted labels:")
    for label, score in zip(result["labels"][:3], result["scores"][:3]):
        print(f"    • {label}: {score:.3f}")
    print()

Review: Although marine expeditions involve months of harsh sea conditions and mechanical failures, the discovery of thriving deep-sea ecosystems near hydrothermal vents makes the research team deeply appreciative of the vessel's advanced life-support systems.
  Top predicted labels:
    • grateful: 0.990
    • positive: 0.932
    • negative: 0.019

Review: While the oceanographic institution routinely provides state-of-the-art sonar equipment and research funding, their persistent refusal to address crew exhaustion and safety concerns leaves researchers feeling completely expendable during offshore missions.
  Top predicted labels:
    • negative: 0.980
    • toxic relationship: 0.946
    • emotional neglect: 0.761

[transformers] You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

Review: Conducting deep-sea trench investigations creates a baffling dynamic; the excitement of gathering unprecedented biological data is immediately offset by overwhelming burnout and safety anxieties, leaving the crew's morale in an ongoing deadlock.
  Top predicted labels:
    • toxic relationship: 0.808
    • negative: 0.705
    • emotional neglect: 0.169

Review: The research team collects ocean salinity measurements every morning at six o'clock, logging standard hydrological metrics into the marine database without performing further biological sampling.
  Top predicted labels:
    • positive: 0.235
    • grateful: 0.075
    • toxic relationship: 0.053

In [5]:
support_ticket="My laptop screen turns completely black whanever I plug in the charger ."
topic_labels=["billing","hardware problem","software bug","account hack"]
result=classifier(support_ticket,candidate_labels=topic_labels)
for label,score in zip(result["labels"],result["scores"]):
  print(f"{label:>20s}:{score:.3f}")

    hardware problem:0.688
             billing:0.167
        account hack:0.086
        software bug:0.059

In [6]:
support_ticket = "The automated gantry crane failed mid-operation, leaving four 40ft containers suspended and halting all loading on Dock B."

topic_labels = [
    "equipment failure",
    "hazmat compliance issue",
    "billing dispute",
    "vessel scheduling delay",
    "container tracking error",
    "weight imbalance warning"
]

result = classifier(support_ticket, candidate_labels=topic_labels)

for label, score in zip(result["labels"], result["scores"]):
    print(f"{label:>20s}:{score:.3f}")

   equipment failure:0.939
vessel scheduling delay:0.028
weight imbalance warning:0.015
container tracking error:0.012
hazmat compliance issue:0.003
     billing dispute:0.003

In [7]:
support_ticket = ("Bunkering was suspended midway because the fuel supply barge delivered contaminated low-sulfur oil, halting our departure until fuel testing completes.")


topic_labels = [
    "port congestion",
    "adverse weather delay",
    "bunkering and fuel issue",
    "customs clearance delay",
    "engine breakdown",
    "pilotage and tugboat shortage"
]

result = classifier(support_ticket, candidate_labels=topic_labels)

for label, score in zip(result["labels"], result["scores"]):
    print(f"{label:>20s}:{score:.3f}")

bunkering and fuel issue:0.972
pilotage and tugboat shortage:0.009
adverse weather delay:0.006
customs clearance delay:0.006
    engine breakdown:0.005
     port congestion:0.003

In [8]:
support_ticket = "Our production API endpoints are returning 500 internal server errors after the latest deployment, blocking all mobile app logins."


topic_labels = [
    "production outage",
    "scope creep",
    "billing discrepancy",
    "infrastructure error",
    "security vulnerability",
    "code deployment failure"
]

result = classifier(support_ticket, candidate_labels=topic_labels)

for label, score in zip(result["labels"], result["scores"]):
    print(f"{label:>20s}:{score:.3f}")

   production outage:0.823
infrastructure error:0.098
code deployment failure:0.035
         scope creep:0.025
security vulnerability:0.015
 billing discrepancy:0.004

In [9]:
support_tickets = [
    "The voice AI agent fails to parse regional accents and Marathi dialects when district bank customers inquire about agricultural loan status.",
    "During peak branch hours, the chatbot experiences API timeouts when fetching account balances from the core banking system (CBS).",
    "The AI agent inadvertently revealed a customer's microfinance loan balance to an unverified phone number during an automated status check.",
    "The bank management requested an unplanned module to handle PM-Kisan scheme eligibility checks before the next sprint deadline."
]

topic_labels = [
    "dialect parsing issue",
    "CBS integration failure",
    "data privacy leak",
    "scope expansion",
    "intent classification error",
    "latency bottleneck"
]

result = classifier(support_ticket, candidate_labels=topic_labels)

for label, score in zip(result["labels"], result["scores"]):
    print(f"{label:>20s}:{score:.3f}")

  latency bottleneck:0.338
     scope expansion:0.252
CBS integration failure:0.211
   data privacy leak:0.106
dialect parsing issue:0.048
intent classification error:0.045

**Generating self sentment analysis model**

In [10]:
!pip install -q transformers datasets accelerate -u
print("Setup Complete.")

Usage:
  pip3 install [options] <requirement specifier> [package-index-options] ...
  pip3 install [options] -r <requirements file> [package-index-options] ...
  pip3 install [options] [-e] <vcs project url> ...
  pip3 install [options] [-e] <local project path> ...
  pip3 install [options] <archive url/path> ...

no such option: -u
Setup Complete.

In [11]:
train_texts = [
    "This movie was absolutely wonderful, I loved every minute of it.",
    "What a fantastic performance, the whole cast was brilliant.",
    "I really enjoyed this book, could not put it down.",
    "The food at this restaurant was delicious and beautifully presented.",
    "Great service, friendly staff, and a lovely atmosphere overall.",
    "This phone exceeded my expectations in every possible way.",
    "An outstanding film with a heartwarming and memorable story.",
    "The hotel room was clean, spacious, and had a stunning view.",
    "I am thrilled with how well this laptop performs every day.",
    "The concert was incredible, the band sounded better than ever.",
    "Such a delightful little cafe, I will definitely be coming back.",
    "The customer support team resolved my issue quickly and politely.",
    "This course explained everything clearly and I learned so much.",
    "The new update makes the app so much faster and easier to use.",
    "Absolutely loved the ending, it tied the whole story together perfectly.",
    "The staff went above and beyond to make our stay comfortable.",
    "A brilliant, thought-provoking novel that I would recommend to anyone.",
    "The pizza was fresh, hot, and full of flavour.",
    "I am very happy with my purchase, it works perfectly.",
    "The trip was wonderful from start to finish.",
    "This movie was boring and the plot made no sense at all.",
    "Terrible customer service, nobody responded to my complaints.",
    "The food arrived cold and tasted quite bland.",
    "I regret buying this phone, it is slow and the battery is weak.",
    "The hotel room was dirty and smelled unpleasant.",
    "What a disappointing performance, the actors seemed uninterested.",
    "The book was confusing and I gave up halfway through.",
    "This app keeps crashing and it is extremely frustrating to use.",
    "The concert was way too loud and poorly organized.",
    "Such an unpleasant experience, the staff were rude to us.",
    "The laptop overheats constantly and the fan is very noisy.",
    "I would not recommend this restaurant, the service was awful.",
    "The ending felt rushed and left too many questions unanswered.",
    "This course was disorganized and hard to follow.",
    "The new update broke several features that used to work fine.",
    "The room was freezing and the heater did not work at all.",
    "I am very unhappy with this purchase, it broke within a week.",
    "The trip was stressful and nothing went according to plan.",
    "The pizza was soggy and clearly not freshly made.",
    "Nobody at the store seemed willing to help us at all.",
]

train_labels = [1]*20 + [0]*20

test_texts = [
    "I had a great time at the beach with my family.",
    "The new restaurant downtown serves amazing pasta.",
    "This gadget works exactly as advertised, very pleased.",
    "The lecture was engaging and easy to understand.",
    "Everything about this vacation exceeded my expectations.",
    "The product stopped working after just two days.",
    "I found the customer service painfully slow and unhelpful.",
    "The movie dragged on and felt far too long.",
    "This laptop keeps freezing and it is very annoying.",
    "The meal was overpriced and honestly quite tasteless.",
]
test_labels = [1, 1, 1, 1, 1, 0, 0, 0, 0, 0]

print(f"Training examples: {len(train_texts)}  |  Test examples: {len(test_texts)}")

Training examples: 40  |  Test examples: 10

In [12]:
from datasets import Dataset
from transformers import AutoTokenizer

model_name = "distilbert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_name)

train_ds=Dataset.from_dict({"text":train_texts,"label":train_labels})
test_ds=Dataset.from_dict({"text":test_texts,"label":test_labels})

def tokenize_function(examples):
  return tokenizer(examples["text"],padding="max_length",truncation=True)

train_ds=train_ds.map(tokenize_function,batched=True)
test_ds=test_ds.map(tokenize_function,batched=True)

train_ds.set_format("torch",columns=["input_ids","attention_mask","label"])
test_ds.set_format("torch",columns=["input_ids","attention_mask","label"])

print(train_ds[0].keys())

config.json:   0%|          | 0.00/483 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

Map:   0%|          | 0/40 [00:00<?, ? examples/s]

Map:   0%|          | 0/10 [00:00<?, ? examples/s]

dict_keys(['label', 'input_ids', 'attention_mask'])

In [13]:
from transformers import AutoModelForSequenceClassification
model=AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=2)
print("Model Loaded. Notice the waring abovw about newly initialized weights- ")
print("That is the brand new classification head , which knows nothing it! ")

model.safetensors: reconstructing file:   0%|          |  0.00B /  268MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_projector.bias    | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
pre_classifier.weight   | MISSING    |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Model Loaded. Notice the waring abovw about newly initialized weights-
That is the brand new classification head , which knows nothing it!

In [14]:
from transformers import TrainingArguments, Trainer


training_args = TrainingArguments(
    output_dir="./sentiment_model",
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=4,
    logging_steps=5,
    save_strategy="no",
    report_to="none",
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_ds,
    eval_dataset=test_ds,
)

trainer.train()

TrainOutput(global_step=20, training_loss=0.4814071774482727, metrics={'train_runtime': 7.9158, 'train_samples_per_second': 20.213, 'train_steps_per_second': 2.527, 'total_flos': 21194783784960.0, 'train_loss': 0.4814071774482727, 'epoch': 4.0})

In [15]:
import numpy as np

predictions = trainer.predict(test_ds)
predicted_labels = np.argmax(predictions.predictions, axis = -1)
accuracy = (predicted_labels == np.array(test_labels)).mean()

print(f"Test Accuracy: {accuracy: .0%}\n")

for text, true_label, pred_label in zip(test_texts, test_labels, predicted_labels):
  mark = "1" if true_label == pred_label else "0"
  print(f"{mark} | true: {true_label} | Pred: {pred_label}  {text}")

Test Accuracy:  100%

1 | true: 1 | Pred: 1  I had a great time at the beach with my family.
1 | true: 1 | Pred: 1  The new restaurant downtown serves amazing pasta.
1 | true: 1 | Pred: 1  This gadget works exactly as advertised, very pleased.
1 | true: 1 | Pred: 1  The lecture was engaging and easy to understand.
1 | true: 1 | Pred: 1  Everything about this vacation exceeded my expectations.
1 | true: 0 | Pred: 0  The product stopped working after just two days.
1 | true: 0 | Pred: 0  I found the customer service painfully slow and unhelpful.
1 | true: 0 | Pred: 0  The movie dragged on and felt far too long.
1 | true: 0 | Pred: 0  This laptop keeps freezing and it is very annoying.
1 | true: 0 | Pred: 0  The meal was overpriced and honestly quite tasteless.

In [16]:
trainer.save_model("./sentiment_model")
tokenizer.save_pretrained("./sentiment_model")
print("Saved to ./sentiment_model - this folder now contained YOUR fine.tuned model.")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Saved to ./sentiment_model - this folder now contained YOUR fine.tuned model.

***Assignment Work***

Adding four new sentences.

In [17]:
train_texts = [
    "This movie was absolutely wonderful, I loved every minute of it.",
    "What a fantastic performance, the whole cast was brilliant.",
    "I really enjoyed this book, could not put it down.",
    "The food at this restaurant was delicious and beautifully presented.",
    "Great service, friendly staff, and a lovely atmosphere overall.",
    "This phone exceeded my expectations in every possible way.",
    "An outstanding film with a heartwarming and memorable story.",
    "The hotel room was clean, spacious, and had a stunning view.",
    "I am thrilled with how well this laptop performs every day.",
    "The concert was incredible, the band sounded better than ever.",
    "Such a delightful little cafe, I will definitely be coming back.",
    "The customer support team resolved my issue quickly and politely.",
    "This course explained everything clearly and I learned so much.",
    "The new update makes the app so much faster and easier to use.",
    "Absolutely loved the ending, it tied the whole story together perfectly.",
    "The staff went above and beyond to make our stay comfortable.",
    "A brilliant, thought-provoking novel that I would recommend to anyone.",
    "The pizza was fresh, hot, and full of flavour.",
    "I am very happy with my purchase, it works perfectly.",
    "The trip was wonderful from start to finish.",
    "This movie was boring and the plot made no sense at all.",
    "Terrible customer service, nobody responded to my complaints.",
    "The food arrived cold and tasted quite bland.",
    "I regret buying this phone, it is slow and the battery is weak.",
    "The hotel room was dirty and smelled unpleasant.",
    "What a disappointing performance, the actors seemed uninterested.",
    "The book was confusing and I gave up halfway through.",
    "This app keeps crashing and it is extremely frustrating to use.",
    "The concert was way too loud and poorly organized.",
    "Such an unpleasant experience, the staff were rude to us.",
    "The laptop overheats constantly and the fan is very noisy.",
    "I would not recommend this restaurant, the service was awful.",
    "The ending felt rushed and left too many questions unanswered.",
    "This course was disorganized and hard to follow.",
    "The new update broke several features that used to work fine.",
    "The room was freezing and the heater did not work at all.",
    "I am very unhappy with this purchase, it broke within a week.",
    "The trip was stressful and nothing went according to plan.",
    "The pizza was soggy and clearly not freshly made.",
    "Nobody at the store seemed willing to help us at all.",
    "I loved python programming",
    "I like punjabi songs",
    "The grapes are sour",
    "Cricket is popular game in India"
]

train_labels = [1]*22 + [0]*22

test_texts = [
    "I had a great time at the beach with my family.",
    "The new restaurant downtown serves amazing pasta.",
    "This gadget works exactly as advertised, very pleased.",
    "The lecture was engaging and easy to understand.",
    "Everything about this vacation exceeded my expectations.",
    "The product stopped working after just two days.",
    "I found the customer service painfully slow and unhelpful.",
    "The movie dragged on and felt far too long.",
    "This laptop keeps freezing and it is very annoying.",
    "The meal was overpriced and honestly quite tasteless.",
    "I like punjabi songs",
    "Cricket is popular game in India"
]
test_labels = [1, 1, 1, 1, 1, 0, 0, 0, 0, 0,1,1]

print(f"Training examples: {len(train_texts)}  |  Test examples: {len(test_texts)}")

Training examples: 44  |  Test examples: 12

In [18]:
from datasets import Dataset
from transformers import AutoTokenizer

model_name = "distilbert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_name)

train_ds = Dataset.from_dict({"text": train_texts, "label": train_labels})
test_ds = Dataset.from_dict({"text": test_texts, "label": test_labels})

def tokenizer_fn(batch):
  return tokenizer(batch["text"], truncation = True, padding="max_length", max_length=12)

train_ds = train_ds.map(tokenizer_fn, batched=True)
test_ds = test_ds.map(tokenizer_fn, batched=True)

print(train_ds[0].keys())

Map:   0%|          | 0/44 [00:00<?, ? examples/s]

Map:   0%|          | 0/12 [00:00<?, ? examples/s]

dict_keys(['text', 'label', 'input_ids', 'token_type_ids', 'attention_mask'])

In [19]:
from transformers import AutoModelForSequenceClassification
model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=2
)

print("Model Loaded")
print("that is  the brand new classification head,which knows nothing yet ")

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_projector.bias    | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
pre_classifier.weight   | MISSING    |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |
pre_classifier.bias     | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Model Loaded
that is  the brand new classification head,which knows nothing yet

In [20]:
from transformers import TrainingArguments, Trainer

Training_args = TrainingArguments(
    output_dir="./sentiment_model1",
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=4,
    logging_steps=5,
    save_strategy="no",
    report_to="none",
)

trainer=Trainer(
    model=model,
    args=Training_args,
    train_dataset=train_ds,
    eval_dataset=test_ds
)

trainer.train()

TrainOutput(global_step=24, training_loss=0.5394380142291387, metrics={'train_runtime': 1.0734, 'train_samples_per_second': 163.969, 'train_steps_per_second': 22.359, 'total_flos': 546428019456.0, 'train_loss': 0.5394380142291387, 'epoch': 4.0})

In [21]:
import numpy as np

predictions = trainer.predict(test_ds)
predicted_labels = np.argmax(predictions.predictions, axis = -1)
accuracy = (predicted_labels == np.array(test_labels)).mean()

print(f"Test Accuracy: {accuracy: .0%}\n")

for text, true_label, pred_label in zip(test_texts, test_labels, predicted_labels):
  mark = "✅" if true_label == pred_label else "❌"
  print(f"{mark} | true: {true_label} | Pred: {pred_label}  {text}")

Test Accuracy:  83%

✅ | true: 1 | Pred: 1  I had a great time at the beach with my family.
✅ | true: 1 | Pred: 1  The new restaurant downtown serves amazing pasta.
✅ | true: 1 | Pred: 1  This gadget works exactly as advertised, very pleased.
✅ | true: 1 | Pred: 1  The lecture was engaging and easy to understand.
✅ | true: 1 | Pred: 1  Everything about this vacation exceeded my expectations.
✅ | true: 0 | Pred: 0  The product stopped working after just two days.
✅ | true: 0 | Pred: 0  I found the customer service painfully slow and unhelpful.
✅ | true: 0 | Pred: 0  The movie dragged on and felt far too long.
✅ | true: 0 | Pred: 0  This laptop keeps freezing and it is very annoying.
✅ | true: 0 | Pred: 0  The meal was overpriced and honestly quite tasteless.
❌ | true: 1 | Pred: 0  I like punjabi songs
❌ | true: 1 | Pred: 0  Cricket is popular game in India

In [22]:
trainer.save_model("./sentiment_model1")
tokenizer.save_pretrained("./sentiment_model1")
print("Saved to ./sentiment_model1 - this folder now contained YOUR fine.tuned model.")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Saved to ./sentiment_model1 - this folder now contained YOUR fine.tuned model.